apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-backend-deployment
  labels:
    app: {{ .Values.name }}-backend
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}-backend
  template:
    metadata:
      labels:
        app: {{ .Values.name }}-backend
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
        fsGroup: 1501
      automountServiceAccountToken: false
      containers:
      - name: pmp-flask-app
        image: {{ .Values.deployment.container.backendImage }}
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          runAsNonRoot: true
          runAsUser: 1501
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
          runAsGroup: 1501